parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Selene\CMSBundle\:
        resource: '../src/*'

    Selene\CMSBundle\Controller\:
        resource: '../src/Controller/*'
        public: true
    Selene\CMSBundle\Repository\:
        resource: '../src/Repository/*'
        # tags: ['doctrine.repository_service']
        public: true

    Selene\CMSBundle\Maker\:
        class: '../src/Maker/MakerController'
        tags: ['maker.command']
        public: true
        arguments:
          - '@maker.php_compat_util'
