parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Selene\CMSBundle\:
        resource: '../src/*'

    Selene\CMSBundle\Controller\:
        resource: '../src/Controller/*'
        public: true
    Selene\CMSBundle\Repository\:
        resource: '../src/Repository/*'
        # tags: ['doctrine.repository_service']
        public: true

    # Selene\CMSBundle\DependencyInjection\Compiler\SidebarCompilerPass:
    #     tags: ['seleneCMS.sidebar']
    # seleneCMS.sidebar_service_collector:
    #     class: SeleneCMS\Service\SidebarCollector
    Selene\CMSBundle\Interface\:
        resource: '../src/Interfaces/*'
          # tags: ['seleneCMS.sidebar']
